config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',                 to: 'static_pages#help'
  get    '/about',                to: 'static_pages#about'
  get    '/contact',              to: 'static_pages#contact'
  get    '/signup',               to: 'users#new'
  get    '/clock_in',             to: 'users#clock_in'
  get    '/clock_out',            to: 'users#clock_out'
  get    '/attendance_edit/:id',  to: 'users#attendance_edit'
  get    '/attendance_save',      to: 'users#attendance_save'
  post   '/attendance_save',      to: 'users#attendance_save'
  patch  '/attendance_save',      to: 'users#attendance_save'
  get    '/besic_info/:id/:from', to: 'users#besic_info'
  get    '/login',                to: 'sessions#new'
  post   '/login',                to: 'sessions#create'
  delete '/logout',               to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :shift, dependent: :destroy
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
 # アカウントを有効にする
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest:  User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # パスワード再設定用メールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = email.downcase
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # 渡されたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  
  <% if user.admin %>
    管理者 |
  <% end %>
  
  <%= link_to user.name, user %>
  
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to '基本時間設定', controller: 'users', action: 'besic_info', id: user.id, from: 'i' %>
    | <%= link_to '削除', user, method: :delete, data: { confirm: '本当に削除しますか？' } %>
  <% end %>
</li>

app/views/users/attendance_edit.html.erb
<h1>
  勤怠編集
  <%= @is_admin ? "（編集対象者：#{@user.name}）" : nil; %>
</h1>

<div class='row'>
  <div class='margin-b-10'>
    <%= link_to '勤怠ページに戻る', { controller: 'users', action: 'show', id: params[:id], q: @query.to_i }, class: 'btn btn-primary btn-font-color' %>
  </div>
  
  <div class='margin-b-10'>
    <%= link_to '前月へ', "/attendance_edit/#{params[:id]}?q=#{@query.to_i-1}", class: 'btn btn-primary btn-font-color' %>
    <%= @target_date.year %>年<%= @target_date.month %>月　時間管理表
    <% if !@is_future %>
      <%= link_to '翌月へ', "/attendance_edit/#{params[:id]}?q=#{@query.to_i+1}", class: 'btn btn-primary btn-font-color' %>
    <% end %>
  </div>
  
  <%= form_for @user, url: attendance_save_path do |f| %>
    <table class='table-design margin-b-10'>
      <tbody>
        <tr>
          <th class='width-5'>日付</th>
          <th class='width-5'>曜日</th>
          <th class='width-20'>出社時間</th>
          <th class='width-20'>退社時間</th>
          <th>備考</th>
        </tr>

        <% @shift.each do |shift| %>
          <tr>
            <td class='width-5'><%= shift.date.to_date.strftime('%-m/%-d') %></td>
            <td class='width-5'><%= @wday[shift.date.to_date.wday] %></td>
           
            <%= fields_for 'shifts[]', shift do |s| %>
              <td class='width-20 padding-a-5'><%= s.time_field :start_time, value: s.object.start_time, class: 'form-control height_i margin-n' %></td>
              <td class='width-20 padding-a-5'><%= s.time_field :end_time, value: s.object.end_time, class: 'form-control height_i margin-n' %></td>
            <% end %>
            
            <td></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.hidden_field :query, value: @query %>
    
    <div class='margin-b-10 padding-l-15'>
      <div class='width-49 inline-block padding-r-10 padding-l-10'>
        <%= link_to 'キャンセル', { controller: 'users', action: 'show', id: params[:id] }, class: 'btn btn-primary width-100 btn-font-color' %>
      </div>
      <div class='width-49 inline-block padding-r-10 padding-l-10'>
        <%= f.submit '保存する', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>
<br>

app/views/users/besic_info.html.erb
<% provide(:title, 'Edit user') %>
<h1><%= @user.name %>の基本情報の更新</h1>

<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :designation_work_hours, '指定勤務時間' %>
      <%= f.select :designation_work_hours, @hour_list,  prompt: '--', class: 'form-control' %>
      
      <%= f.label :besic_work_hours, '基本時間' %>
      <%= f.select :besic_work_hours, @hour_list,  prompt: '--', class: 'form-control' %>
      
      <%= f.hidden_field :from, value: @from %>
      
      <%= f.submit '更新する', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, '名前' %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, 'メールアドレス' %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :affiliation, '所属' %>
      <%= f.text_field :affiliation, class: 'form-control' %>

      <%= f.label :password, 'パスワード' %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, 'パスワード(確認)' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit '更新する', class: 'btn btn-primary' %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails">画像を変更</a>
    </div>
  </div>
</div>

app/views/users/error_show.html.erb
<% provide(:title, 'アクセスエラー') %>

<div class="access-error">本人以外の勤怠ページにはアクセスできません</div>

<div class="col-md-4 col-md-offset-4 margin-t-70">
  <%= link_to '戻る', { controller: 'users', action: 'show', id: session[:user_id], q: @query.to_i }, class: 'btn btn-primary width-100' %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>ユーザーリスト</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>新規作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :affiliation, '所属' %>
      <%= f.text_field :affiliation, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード(確認)" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "作成する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class='row'>
  <aside class='col-md-4'>
    <section>
      <h1>
        <%= gravatar_for @user %>
        氏名　<%= @user.name %><br>
        所属　<%= @user.affiliation %>
      </h1>
    </section>
  </aside>
  
  <table class='margin-b-10'>
    <tr>
      <th class='width-20'>出勤日数</th>
      <th class='width-20'>指定勤務時間</th>
      <th class='width-20'>基本時間</th>
      <th class='width-20'>初日</th>
      <th class='width-20'>締め</th>
    </tr>
    <tr>
      <td class='width-20'><%= @total_days %>日</td>
      <td class='width-20'>
        <%= @user[:designation_work_hours].present? ? @user[:designation_work_hours] + '時間': '未設定'; %>
      </td>
      <td class='width-20'>
        <%= @user[:besic_work_hours].present? ? @user[:besic_work_hours] + '時間': '未設定'; %>
      </td>
      <td class='width-20'><%= @target_date.month %>/1</td>
      <td class='width-20'><%= @target_date.month %>/<%= @end_day %></td>
    </tr>
  </table>

  <% if @today.to_date.strftime('%-m') >= @target_date.strftime('%-m') %>
    <div class='margin-b-10'>
      <%= link_to '勤怠を編集', { controller: 'users', action: 'attendance_edit', id: params[:id], q: @query.to_i }, class: 'btn btn-primary btn-font-color' %>
    </div>
  <% end %>
    
  <div class='margin-b-10'>
    <%= link_to '前月へ', "/users/#{params[:id]}?q=#{@query.to_i - 1}", class: 'btn btn-primary btn-font-color' %>
    <%= @target_date.year %>年<%= @target_date.month %>月　時間管理表
    <%= link_to '翌月へ', "/users/#{params[:id]}?q=#{@query.to_i + 1}", class: 'btn btn-primary btn-font-color' %>
  </div>
  
  <%# 勤怠表 ここから=============================================================== %>
  <table class='table-design'>
    <tr>
      <th class='width-5'>日付</th>
      <th class='width-5'>曜日</th>
      <th class='width-12'>出社時間</th>
      <th class='width-7'></th>
      <th class='width-12'>退社時間</th>
      <th class='width-7'></th>
      <th class='width-12'>勤務時間</th>
      <th class='width-'>備考</th>
    </tr>
    <% @list_months.each do |day| %>
      <% @total_time += day[:work_hours].to_f %>
      <tr>
        <td class='width-5'><%= day[:date].to_date.strftime('%-m/%-d') %></td>
        <td class='width-5'><%= day[:wday] %></td>
        <td class='width-12'><%= day[:start_time] %></td>
        <td class='width-7'>
          <% if day[:is_clock_in] === 1 %>
            <%= link_to '出社', clock_in_path(user_id: params[:id]), class: 'btn btn-primary padding-tb-2 padding-rl-20' %>
          <% end %>
        </td>
        <td class='width-12'><%= day[:end_time] %></td>
        <td class='width-7'>
          <% if day[:is_clock_out] === 1 %>
            <%= link_to '退社', clock_out_path(user_id: params[:id]), class: 'btn btn-primary padding-tb-2 padding-rl-20' %>
          <% end %>
        </td>
        <td class='width-12'><%= day[:work_hours] === nil ? '' : "#{day[:work_hours]}時間" %></td>
        <td class='width-'></td>
      </tr>
    <% end %>
    
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>勤務時間の合計</td>
      <td><%= @total_time.round(1) %>時間</td>
      <td></td>
    </tr>
  </table>
  <%# 勤怠表 ここまで=============================================================== %>
</div>
<br>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>