config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',                 to: 'static_pages#help'
  get    '/about',                to: 'static_pages#about'
  get    '/contact',              to: 'static_pages#contact'
  get    '/signup',               to: 'users#new'
  get    '/clock_in',             to: 'users#clock_in'
  get    '/clock_out',            to: 'users#clock_out'
  get    '/attendance_edit/:id',  to: 'users#attendance_edit'
  get    '/attendance_save',      to: 'users#attendance_save'
  post   '/attendance_save',      to: 'users#attendance_save'
  patch  '/attendance_save',      to: 'users#attendance_save'
  get    '/besic_info/:id/:from', to: 'users#besic_info'
  get    '/login',                to: 'sessions#new'
  post   '/login',                to: 'sessions#create'
  delete '/logout',               to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in? %>
      <%= link_to '勤怠管理システム', current_user, id: 'logo' %>
    <% else %>
      <%= link_to '勤怠管理システム', { controller: 'static_pages', action: 'home' }, id: 'logo' %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "トップ", current_user %></li>
          
          <% if @is_admin %>
            <li><%= link_to 'ユーザーリスト', users_path %></li>
            <li>
              <%= link_to '基本時間設定', controller: 'users', action: 'besic_info', id: @login_user.id, from: 'h' %>
            </li>
          <% end %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to '設定', edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'ログイン', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      
      <%= debug(params) if Rails.env.development? %>
      
      <%= yield %>
      <!--<% render 'layouts/footer' %>-->
    </div>
  </body>
</html>